### ISSUE TITLE
Causing errors in makeLogRecord from the standard library

### ISSUE THREAD

**Issue by kindofluke** [glentner/CmdKit#20]
As part of the 2.7 release of cmdkit, the `LogRecord` class is reimplemented by cmdkit to add support for colors and other nice features. However in applications with highly customized logging implementations, the `cmdkit.LogRecord` can interfere with creation of LogRecord using the [makeLogRecord function](https://docs.python.org/3/library/logging.html#logging.makeLogRecord). Per Python documentation, `makeLogRecord` is the preferred way to create log records with custom attributes. 

Here is the error 

```python
Python 3.9.9 (main, Dec 21 2021, 20:28:12)
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> record = logging.makeLogRecord({"foo":"bar"})
>>> import cmdkit
>>> record = logging.makeLogRecord({"foo":"bar"})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/luke.shulman/.asdf/installs/python/3.9.9/lib/python3.9/logging/__init__.py", line 399, in makeLogRecord
    rv = _logRecordFactory(None, None, "", 0, "", (), None, None)
  File "/Users/luke.shulman/Projects/cmd_venv/lib/python3.9/site-packages/cmdkit/logging.py", line 179, in __init__
    self.relative_name = self.name.split('.', 1)[-1]
AttributeError: 'NoneType' object has no attribute 'split'
```

Looking at the stdlib implementation of make log record https://github.com/python/cpython/blob/6bc889aedc11cc8e0b9f57948a3d528ad2685497/Lib/logging/__init__.py#L417 the LogRecord is first created with `None` as the name. cmdkit is then trying to split on that name.

**Comment by glentner** [comment]
Thank you for filing the issue. 

I think this is actually a bit more nuanced than you suggest, but I see how you are being impacted, so let me contribute to the conversation constructively. 

The `makeLogRecord` function is not in fact the preferred way to _extend_ log records. If you look at the standard library's documentation, it suggests the following for extending log records with additional attributes (https://docs.python.org/3/library/logging.html)

```python
old_factory = logging.getLogRecordFactory()

def record_factory(*args, **kwargs):
    record = old_factory(*args, **kwargs)
    record.custom_attribute = 0xdecafbad
    return record

logging.setLogRecordFactory(record_factory)
```

This is in-effect what I've done by extending the class. Any other library that has done something similar by calling `getLogRecordFactory` will have pinned the factory to the module, so when CmdKit imports that class and extends it, it has the intended effect. Looking at this now though, if anyone extends the `LogRecord` by defining a _function_ as the documentation does, it will be a problem because I cannot inherit from that, so this is worth looking into.

With regard to `makeLogRecord`, the standard library documentation suggests this is a means to reconstruct a `LogRecord` instance from the underlying data `__dict__` of some other `LogRecord` instance. For example, the `SocketHandler` suggests this as a way to re-constitute records whose underlying `__dict__` has been written to a socket. In these cases, the standard attributes would be present in that `__dict__` (i.e., the `name`). 

Passing an arbitrary dictionary like `{'foo': 'bar'}` is not the intended use case here. It doesn't fail initially because there is merely no collision _yet_ with a missing attribute (assigned `None`). However, if you actually passed that to a handler who attempted to format it, you would in fact get a nasty response or an unintended message because `name` was missing.

The implementation of `makeLogRecord` passes these because they are meant as "harmless" temporary values that will be immediately replaced by the passed data. To your point, I have actually made them harmful by attempting to use existing attributes. I think it would still be a problem even if you passed a fully formed `__dict__`.

I think just putting simple checks for _falsy_-ness and just assigning the equivalent would protect against this corner case. For example, maybe:

```python
if self.name:
    self.relative_name = self.name.split('.', 1)[-1]
else:
    self.relative_name = None
```

**Comment by glentner** [comment]
Release 2.7.2 contains the fix.

**Comment by kindofluke** [comment]
Thanks so much!
